### ISSUE TITLE
The source 'IQueryable' doesn't implement 'IAsyncEnumerable<>

### ISSUE THREAD

**Issue by sraxler** [willianantunes/drf-like-paginations#6]
Facing this issue while trying to read from MongoDB using AsQueryable(). 
"Only sources that implement 'IAsyncEnumerable' can be used for Entity Framework asynchronous operations."

**Comment by willianantunes** [comment]
Hi, @Savio-Fernandes-Git ! I think this is OK actually. This library is intended for Entity Framework only. However, you're using MongoDB, so unpredictable outcomes are indeed expected.
